% EAN 13 barcode generator

clc

% function for calculating check sum
checkSum = @(code) mod(-code*repmat([1; 3],[6, 1]),10);

CodeTable = [...
    0,0,0,1,1,0,1;...
    0,0,1,1,0,0,1;...
    0,0,1,0,0,1,1;...
    0,1,1,1,1,0,1;...
    0,1,0,0,0,1,1;...
    0,1,1,0,0,0,1;...
    0,1,0,1,1,1,1;...
    0,1,1,1,0,1,1;...
    0,1,1,0,1,1,1;...
    0,0,0,1,0,1,1
    ];


% L-code
Code.L = @(n) CodeTable(n+1,:);

% R-code (bit-wise negation of the L-code)
Code.R = @(n) double(~CodeTable(n+1,:));

% G-code (reverse of R-code)
Code.G = @(n) flip(double(~CodeTable(n+1,:)),2);

FirstDigit = ... 
   ['LLLLLL';...
    'LLGLGG';...
    'LLGGLG';...
    'LLGGGL';...
    'LGLLGG';...
    'LGGLLG';...
    'LGGGLL';...
    'LGLGLG';...
    'LGLGGL';...
    'LGGLGL'];


% first digit
Code.FirstDigit = @(n) FirstDigit(n,:);


BarcodeNum = [6, 2, 0, 1, 2, 3, 4, 1, 2, 3, 4, 5];

fd = BarcodeNum(1);
BarcodeNum = circshift(BarcodeNum,[2,-1]);
BarcodeNum(end + 1) = checkSum(BarcodeNum);
d = [Code.FirstDigit(fd), 'RRRRRR'];
e = zeros(12,7);

for i = 1:12
    e(i,:) = Code.(d(i))(BarcodeNum(i));
end

bar_width = 2;
barcode = repmat(kron(reshape(e,1,numel(e)),ones(1,2)),100,1);

imshow(barcode)