function rectangles_2

screen = get(0, 'ScreenSize');
screen(1:2) = [];
figPos = [screen/4, screen/2];


figure(...
    'Position', figPos,...
    'Color', 0.3*[1, 1, 1],...
    'MenuBar', 'no',...
    'NumberTitle', 'off',...
    'Name', 'Rectangles II',...
    'WindowButtonMotionFcn', @moveRectangle)
axes(...
    'Position', [0, 0, 1, 1],...
    'Visible', 'off',...
    'DataAspectRatio', [1, 1, 1],...
    'XLim', [-1, 1],...
    'YLim', [0, 1])
patch(...
    'XData', [-0.3, 0, 0, -0.3],...
    'YData', [0.3, 0.3, 0.7, 0.7],...
    'FaceColor', [1, 1, 1],...
    'FaceAlpha', 0.7,...
    'EdgeColor', 'none',...
    'Tag', 'diskL')

patch(...
    'XData', [0, 0.3, 0.3, 0],...
    'YData', [0.3, 0.3, 0.7, 0.7],...
    'FaceColor', [1, 1, 1],...
    'FaceAlpha', 0.7,...
    'EdgeColor', 'none',...
    'Tag', 'diskR')
end


function moveRectangle(~, ~)

dL = findobj('Tag', 'diskL');
dR = findobj('Tag', 'diskR');

mousePos = get(gca, 'CurrentPoint');
t = (mousePos(1)+1)/2;
s = mousePos(1,2);

f = @(t, a, b) a.*(1-t) + b.*t;

rL = f(s, 0.45, 0.05);
rR = f(s, 0.05, 0.45);

set(dL,...
    'XData', f(t, [-1-rL, -1+rL, -1+rL, -1-rL], [1-rL, 1+rL, 1+rL, 1-rL]),...
    'YData', [0.5-rL, 0.5-rL, 0.5+rL, 0.5+rL])
set(dR,...
    'XData', f(t, [1-rR, 1+rR, 1+rR, 1-rR],  [-1-rR, -1+rR, -1+rR, -1-rR]),...
    'YData', [0.5-rR, 0.5-rR, 0.5+rR, 0.5+rR])

end