function rectangles_1

scr = get(0, 'ScreenSize');
scr(1:2) = [];
fig_pos = [scr/4, scr/2];


figure(...
    'Position', fig_pos,...
    'Color', 0.3*[1, 1, 1],...
    'MenuBar', 'no',...
    'NumberTitle', 'off',...
    'Name', 'Rectangles I',...
    'WindowButtonMotionFcn' , @move_rectangle)
axes(...
    'Position', [0, 0, 1, 1],...
    'Visible', 'off',...
    'DataAspectRatio', [1, 1, 1],...
    'XLim', [-1, 1],...
    'YLim', [0, 1])
rectangle(...
    'Position', [-0.3, 0.3, 0.3, 0.3],...
    'FaceColor', 0.5*[1, 1, 1],...
    'EdgeColor', 'none',...
    'Tag', 'diskL')

rectangle(...
    'Position', [0, 0.3, 0.3, 0.3],...
    'FaceColor', 0.5*[1, 1, 1],...
    'EdgeColor', 'none',...
    'Tag', 'diskR')
end


function move_rectangle(~, ~)

dL = findobj('Tag', 'diskL');
dR = findobj('Tag', 'diskR');

mouse_pos = get(gca, 'CurrentPoint');
t = (mouse_pos(1)+1)/2;

f = @(t, a, b) a.*(1-t) + b.*t;

set(dL,...
    'Position', [f(t, [-0.9, 0.05], [-0.1, 0.45]), f(t,0.9,0.1)*[1, 1]],...
    'FaceColor', f(t, 1, 0.3)*[1, 1, 1])
set(dR,...
    'Position', [f(t, [0, 0.45], [0, 0.05]), f(t, 0.1, 0.9)*[1, 1]],...
    'FaceColor', f(t, 0.3, 1)*[1, 1, 1])

end