n = 100000;

screenSize = get(0, 'ScreenSize');
screenSize = screenSize(3:4);
dir = [...
    1,  0;...   % move right
    0,  1;...   % move up
    -1, 0;...   % move left
    0, -1];     % move down

figure(...
    'MenuBar', 'figure',...
    'Name', 'Random Walk in 2D',...
    'NumberTitle', 'off',...
    'Position', [screenSize/4, screenSize/2],...
    'Color', [1, 1, 1],...
    'Colormap', [1, 1, 1; 0, 0, 0])
axes('Visible', 'off',...
     'DataAspectRatio', [1 1 1])

steps = randi([1, 4], [1,n]);
walk = cumsum([[0, 0]; dir(steps,:)]);


line('XData', walk(:,1), 'YData', walk(:,2))