clc
close all
clear all

% paraméterek
m=0.4;          % inga tömege
M=0.6;          % kocsi tömege
b=0.3;         
g=9.81;         % gravitációs gyorsulás
J=0.008;        % tehetetlenségi nyomaték?
l=0.14;         % inga hossza
%s = tf('s');
q = (M+m)*(J+m*l^2)-(m*l)^2;

screen = get(0, 'ScreenSize')
screen(1:2) = [];
figPos = [1*screen(1)/10, 0.8*screen(2)/4,8*screen(1)/10, 3*screen(2)/4];

handles.fig = figure(1);
set(handles.fig,...
    'Position', figPos,...
    'MenuBar', 'no',...
    'Color', [1 1 1],...
    'Name', 'Pendulum',...
    'NumberTitle', 'off')

handles.ax = axes(...
    'Box', 'on',...
    'DataAspectRatio', [1, 1, 1],...
    'XLim', [-10,10],...
    'YLim', [-5, 10]);

line('XData', get(handles.ax, 'XLim'),...
     'YData', [0, 0],...
     'Color', [0.1, 0.1, 0.1],...
     'LineWidth', 2);

% simulation data
deg = pi/180;               % conversion constant deg -> rad 
sim_data.pos = -1;
sim_data.vel = 0;
sim_data.angle = 12*deg;
sim_data.angvel = 0;

x=sim_data.pos;
fi=sim_data.angle;
l = 6;

%kocsi
cart(1) = rectangle('Position', [x-1, 0.3, 2, 1],...
          'Curvature', [0.3, 0.6],...
          'FaceColor', [0.7,0.7,0.7],...
          'EdgeColor', 'k',...
          'LineWidth', 2);
%kerekek
cart(2) = rectangle('Position', [x-0.65, 0, 0.3, 0.3],...
          'Curvature', [1, 1],...
          'EdgeColor', [0,0,0],...
          'FaceColor', [0.2,0.2,0.2],...
          'LineWidth', 3);
cart(3) = rectangle('Position', [x+0.35, 0, 0.3, 0.3],...
          'Curvature', [1, 1],...
          'EdgeColor', [0,0,0],...
          'FaceColor', [0.2,0.2,0.2],...
          'LineWidth', 3);


%csuklo
patch('XData', [x-0.2, x+0.2, x],...
      'YData', [1.3, 1.3, 1.55],...
      'EdgeColor', 'black',...
      'FaceColor', [0.8, 0.3, 0.3],...
      'LineWidth', 2)
%inga
d = 0.1;
rod = [-d, d, d, -d;
        0, 0, l, l];
rod = [cos(fi), sin(fi); -sin(fi), cos(fi)]*rod;

patch('XData', rod(1,:)+x,...
      'YData', rod(2,:)+1.55,...
      'EdgeColor', 'black',...
      'FaceColor', [0.2, 0.2, 0.9],...
      'LineWidth', 2)
  
rectangle('Position', [x-0.1, 1.55-0.1, 0.2, 0.2],...
          'Curvature', [1, 1],...
          'EdgeColor', [0,0,0],...
          'FaceColor', [1,1,1],...
          'LineWidth', 1);

      
sim_out=sim('inga2s.slx')
%% Irtech HF 1. Feladat
%�tviteli f�ggv�ny er�/elfordul�s
P_pend = (m*l*s/q)/(s^3 + (b*(J + m*l^2))*s^2/q - ((M + m)*m*g*l)*s/q - b*m*g*l/q);
% p�lusok meghat�roz�sa
poles = pole(P_pend)
%T=-1/poles
%rlocus(P_pend);
%title('Root Locus of Plant (under Proportional Control)')
