function [] = DrawIng(l,x,fok)
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here
fi=fok*pi/180;
%kocsi
rectangle('Position', [x-1, 1.3, 2, 1],...
          'Curvature', [0.3, 0.6],...
          'FaceColor', [0.7,0.7,0.7],...
          'EdgeColor', 'k',...
          'LineWidth', 3);
      %kerekek
rectangle('Position', [x-0.65, 1, 0.3, 0.3],...
          'Curvature', [1, 1],...
          'EdgeColor', [0,0,0],...
          'FaceColor', [0.2,0.2,0.2],...
          'LineWidth', 3);
rectangle('Position', [x+0.35, 1, 0.3, 0.3],...
          'Curvature', [1, 1],...
          'EdgeColor', [0,0,0],...
          'FaceColor', [0.2,0.2,0.2],...
          'LineWidth', 3);
      %csuklo
patch('XData', [x-0.2, x+0.2, x],...
      'YData', [2.3, 2.3, 2.65],...
      'EdgeColor', 'black',...
      'FaceColor', [0.8, 0.3, 0.3],...
      'LineWidth', 2)
  %inga
% patch('XData', [x-0.1*cos(fi), x+0.1*cos(fi),  x+l*sin(fi)+0.1*cos(fi),x+l*sin(fi)-0.1*cos(fi)],...
%       'YData', [2.65+0.2*sin(fi)-0.1, 2.65-0.2*sin(fi)-0.1, 2.65+l*cos(fi)-0.2*sin(fi)-0.1, 2.65+l*cos(fi)+0.2*sin(fi)-0.1,],...
%       'EdgeColor', 'black',...
%       'FaceColor', [0.2, 0.2, 0.9],...
%       'LineWidth', 2)
 line(...
    'XData', [x, x+l*sin(fi)],...
    'YData', [2.65, 2.65+l*cos(fi)],...
    'LineWidth', 5,...
    'Color', [0, 0, 0]);
rectangle('Position', [x-0.1, 2.55, 0.2, 0.2],...
          'Curvature', [1, 1],...
          'EdgeColor', [0,0,0],...
          'FaceColor', [1,1,1],...
          'LineWidth', 1);

end

