X = [
    2 0 0 16;
    0 0 0 0;
    0 2048 0 2;
    0 0 0 0;
    ];

% justify to the right
clc
disp(X)

scr_size = get(0, 'ScreenSize');
scr_size(1:2) = []; 
fig_size = 250;


handles.fig = figure(...
    'MenuBar', 'none',...
    'Name', '2048',...
    'NumberTitle', 'off',...
    'Position', [scr_size/2-fig_size*[1, 1], 2*fig_size*[1, 1]],...
    'Color', 0.9*[0.8, 0.76, 0.71],...
    'Colormap', [0, 0, 0; 1, 1, 1],...
    'UserData', X);
axes('Visible', 'off')


for i = 1:4
    for j = 1:4
        handles.rec(i,j) = rectangle(...
            'Position', [j-1, 4-i, 0.9, 0.9],...
            'Curvature', 0.1*[1, 1],...
            'FaceColor', [1, 1, 1],...
            'EdgeColor', 'none'...
            );
        handles.text(i,j) = text(...
            'Position', [j-1, 4-i]+0.45,...
            'String', '',...
            'HorizontalAlignment', 'center',...
            'VerticalAlignment', 'middle',...
            'Color', [1, 1, 1],...
            'FontSize', 28,...
            'FontWeight', 'bold');
    end
end

set(handles.fig, 'WindowKeypressFcn', {@keypress_callback, handles})

draw_table(X, handles)




